*       Default starting ecliptic longitude
        lambda1 = 2.40d+02

*	Ecliptic longitude advances
        step = 3.60d+02 / 1.3d+01

*       Size of the camera
        edge = 1.2d+01
        corner = edge * sqrt( 2.0d+00 )

*	Ecliptic latitudes of the FOV centers of the 4 cameras
        betas( 1 ) = -1.8d+01
        betas( 2 ) = -4.2d+01
        betas( 3 ) = -6.6d+01
        betas( 4 ) = -9.0d+01

	c1limit = -6.0d+00
        c1gap = -2.9926d+01
	c2limit = +6.0d+00
	
*       Chip gaps within camera
        gapx = 0.25d+00
	gapy = 0.25d+00
